In [1]:
#%%
import cv2
import math
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pickle
from PIL import Image


Pickle

Deserializing dictionary saved in pickle

In [2]:
Exp_2_pckl={}
path = 'C:/Users/srboval1/OneDrive - Aalto University/Instru/Datafiles/Exp2/Arttu/'
with open(path + 'Exp_design_2_ID.pkl', 'rb') as f:
    Exp_2_pckl = pickle.load(f)

Keys of nested dictionaries; Keys-indexes nested in the first internal dictionary


In [11]:
print('Length of the first mask:', len(Exp_2_pckl[0]["masks"]))
print('Number of masks',len(Exp_2_pckl.keys()))
print('Variables for each mask:',Exp_2_pckl[0].keys())

Length of the first mask: 53
Number of masks 287
Variables for each mask: dict_keys(['masks', 'x', 'y', 'z', 'time', 'area'])


CSV

In [20]:
Exp_2_csv = pd.read_csv(path +'/Exp_design_2.csv', index_col=None) #loading the Arttu's csv file to match the measurement_id and well_id, to be matched with the pckl info

print('Variables for each row-mask:',Exp_2_csv.columns)
#print('Size of csv file:' )
print('Number of masks:',Exp_2_csv.shape[0])
print('Number of unique IDs in csv file:',len(Exp_2_csv["ID"].unique()))
print('Number of groups after measurement and well_id grouping:',(Exp_2_csv.groupby(['measurement_id', 'well_id'])).ngroups)


Variables for each row-mask: Index(['Unnamed: 0', 'seeding_density', 'cell_label', 'well_id',
       'measurement_id', 'matrix', 'ID', 'day'],
      dtype='object')
Number of masks: 287
Number of unique IDs in csv file: 287
Number of groups after measurement and well_id grouping: 178


In [36]:
print(Exp_2_csv.iloc[5]['well_id'])

12


In [12]:

concentration_mapping = {
'2mgml': '1',
'3mM': '2',
'40mM': '3'
}
material_mapping = {
'2mgml': '1',
'3mM': '2',
'40mM': '3'
}
reverse_material_mapping = {
'2mgml':'collagen 2mg/ml',
'3mM':'IPN 2.5mM',
'40mM':'IPN 40mM'
}
cell_mapping = {
'MCF10A': '1',
'DCIS.COM': '2',
'MCF10A.DCIS.COM': '2',
'MCF10AT': '3'
}


In [57]:
pixel_size = 0.32*1e-6

print('List of contour coordinates:',Exp_2_pckl[0]["masks"][0])
print('Linda calculated area [pixels]:',cv2.contourArea(Exp_2_pckl[0]["masks"][0]))
print('re-calculated area in [m]:',cv2.contourArea(Exp_2_pckl[0]["masks"][0])*(0.660535171355723**2))

print('Arttu calculated area:',Exp_2_pckl[0]["area"][0])

List of contour coordinates: [[[ 634 1492]]

 [[ 633 1493]]

 [[ 633 1494]]

 ...

 [[ 637 1492]]

 [[ 636 1492]]

 [[ 635 1492]]]
Linda calculated area [pixels]: 36328.0
re-calculated area in [m]: 15850.15025525776
Arttu calculated area: 13469.269043631683


In [43]:
#%%
pixel_size = 0.32*1e-6
df_collecting = []
df_all = []

def search(key_id):
    well = Exp_2_csv.loc[key_id,'well_id']
    measurement = Exp_2_csv.loc[key_id,'measurement_id']
    cell_line = Exp_2_csv.loc[key_id,'cell_label']
    material = Exp_2_csv.loc[key_id,'matrix']
    day = Exp_2_csv.loc[key_id,'day']
    return well, measurement, cell_line, material, day

for key in Exp_2_pckl.keys() :
    df_temp =[] 

    for i in range(len(Exp_2_pckl[key]["time"])): #looping through time
        mask = Exp_2_pckl[key]["masks"][i]
        time = Exp_2_pckl[key]["time"][i]
        area_Arttu = Exp_2_pckl[key]["area"][i]    

        area = cv2.contourArea(mask)        
        area_µm = area*pixel_size    
        measurement_id = key

        perimeter = cv2.arcLength(mask, closed=True)*pixel_size #perimeter for each contour
        compactness = 4 * math.pi * area_µm  #compactness (spheroid area/area of object with the identical perimeter)
        rect = cv2.minAreaRect(mask) #minimal rectangle
        width, height  = rect[1] #extracting the tuple containing rectangular dimensions
        aspect_ratio = width / height
        convexhull = cv2.convexHull(mask)
        convexhull_perimeter = cv2.arcLength(convexhull, closed=True)*pixel_size #perimeter for each contour
        convexhull_area = cv2.contourArea(convexhull)*pixel_size
        convexity_perimeter = convexhull_perimeter/perimeter
        convexity_area = convexhull_area/area
        well_id,measurement_id, cell, matrix,date = search(key)
        
        info={}
        info = {
            "spheroid_id": key,
            "time_id": i+1,
            "area_Arttu":area_Arttu,
            "area":area,
            "area_µm": area_µm,
            "perimeter": perimeter,
            "compactness": compactness,
            "aspect_ratio": aspect_ratio,
            "convex hull perimeter": convexhull_perimeter,
            "convex hull area": convexhull_area,
            "convexity_perimeter": convexity_perimeter,
            "convexity_area": convexity_area,
            "well_id":well_id,
            "measurement_id":measurement_id,
            "cell_line":cell,
            "matrix":matrix,
            "date":date
            }
        df_temp.append(pd.DataFrame([info]) )  #appending the info to the contours_info, which collects all timestemps
    
    df_collecting.append(pd.concat(df_temp,ignore_index=True)) #lists of dfs are contantenated and appended to df_collecting, thedf_temp is re-initialized

df_all=pd.concat(df_collecting, ignore_index=True)

saving_path= 'C:/Users/srboval1/OneDrive - Aalto University/Instru/Datafiles'
df_all.to_csv(saving_path+'/contours_exp2.csv')  

Visualizing the mask

In [ ]:
#%%
save = 'C:/Users/srboval1/OneDrive - Aalto University/Instru/Datafiles/TimeLapse/'
width, height = 2304, 2304

# Create a blank white image using Pillow and converting it into array


for key in Exp_2_pckl.keys() :
    cell_line = Exp_2_pckl[key]["cell_line"]
    matrix = Exp_2_pckl[key]["matrix"]
    
    blank_image = Image.new('RGB', (width, height), color = (255, 255, 255))
    blank_image_array = np.asarray(blank_image)

    new_image=np.zeros((height, width, 3), np.uint8)


    for i in range(len(Exp_2_pckl[key]["time"])): #looping through time
        mask = Exp_2_pckl[key]["masks"][i]
        spheroid_id = key+1
        blank_image_array= cv2.drawContours(blank_image_array, Exp_2_pckl[key]["masks"][i], -1, (0, 0, 0), 1)
        #print( f'{unique_material}- {unique_line}; min: {min_value} and max {max_value}')

    plt.title(f'{matrix} - {cell_line}; spheroid id: {spheroid_id}') 
    plt.imshow(new_image)
    filename = f'{cell_line}_{matrix}_id_{id}.tiff'

    cv2.imwrite(save+filename, blank_image_array) #saving the contours